# Regions on which to run aws-nuke
regions:
  - eu-west-1
  - global

# aws-nuke requires at least one account be configured in blocklist such as your production accounts
# if you don't want anything there, you can specify a dummy account ID
account-blocklist:
  - "000000000000"

# Account IDs on which you allow aws-nuke to run
accounts:
  470513171732:
    filters:
      CloudFormationStack:
        - type: glob
          property: "Name"
          value: "StackSet-AWSControlTowerBP-*"

      # S3Bucket:
      #   - type: exact
      #     property: "Name"
      #     value: "my-private-bucket-amadou"

      # EC2Instance:
      #   - property: "tag:cloudfaciletag"
      #     value: "true"

# List of resource types to be deleted
resource-types:
  targets:
    - ACMCertificate
    - ACMPCACertificateAuthority
    - ACMPCACertificateAuthorityState
    - AMPWorkspace
    - APIGatewayAPIKey
    - APIGatewayClientCertificate
    - APIGatewayDomainName
    - APIGatewayRestAPI
    - APIGatewayUsagePlan
    - APIGatewayV2API
    - APIGatewayV2VpcLink
    - APIGatewayVpcLink
    - AWSBackupPlan
    - AWSBackupRecoveryPoint
    - AWSBackupSelection
    - AWSBackupVault
    - AWSBackupVaultAccessPolicy
    - AccessAnalyzer
    - AppMeshMesh
    - AppMeshRoute
    - AppMeshVirtualGateway
    - AppMeshVirtualNode
    - AppMeshVirtualRouter
    - AppMeshVirtualService
    - AppStreamDirectoryConfig
    - AppStreamFleet
    - AppStreamFleetState
    - AppStreamImageBuilder
    - AppStreamImageBuilderWaiter
    - AppStreamStack
    - AppStreamStackFleetAttachment
    - AppSyncGraphqlAPI
    - ApplicationAutoScalingScalableTarget
    - ArchiveRule
    - AthenaNamedQuery
    - AthenaWorkGroup
    - AutoScalingGroup
    - AutoScalingPlansScalingPlan
    - BatchComputeEnvironment
    - BatchComputeEnvironmentState
    - BatchJobQueue
    - BatchJobQueueState
    - Budget
    - Cloud9Environment
    - CloudDirectoryDirectory
    - CloudDirectorySchema
    - CloudFormationStack
    - CloudFormationStackSet
    - CloudFormationType
    - CloudFrontDistribution
    - CloudFrontDistributionDeployment
    - CloudFrontOriginAccessIdentity
    - CloudHSMV2Cluster
    - CloudHSMV2ClusterHSM
    - CloudSearchDomain
    - CloudTrailTrail
    - CloudWatchAlarm
    - CloudWatchDashboard
    - CloudWatchEventsRule
    - CloudWatchEventsTarget
    - CloudWatchLogsDestination
    - CloudWatchLogsLogGroup
    - CloudWatchLogsResourcePolicy
    - CodeArtifactDomain
    - CodeArtifactRepository
    - CodeBuildProject
    - CodeCommitRepository
    - CodeDeployApplication
    - CodePipelinePipeline
    - CodeStarConnection
    - CodeStarNotificationRule
    - CodeStarProject
    - CognitoIdentityPool
    - CognitoIdentityProvider
    - CognitoUserPool
    - CognitoUserPoolClient
    - CognitoUserPoolDomain
    - ComprehendDocumentClassifier
    - ComprehendDominantLanguageDetectionJob
    - ComprehendEndpoint
    - ComprehendEntitiesDetectionJob
    - ComprehendEntityRecognizer
    - ComprehendKeyPhrasesDetectionJob
    - ComprehendSentimentDetectionJob
    - ConfigServiceConfigRule
    - ConfigServiceConfigurationRecorder
    - ConfigServiceDeliveryChannel
    - DAXCluster
    - DAXParameterGroup
    - DAXSubnetGroup
    - DataPipelinePipeline
    - DatabaseMigrationServiceCertificate
    - DatabaseMigrationServiceEndpoint
    - DatabaseMigrationServiceEventSubscription
    - DatabaseMigrationServiceReplicationInstance
    - DatabaseMigrationServiceReplicationTask
    - DatabaseMigrationServiceSubnetGroup
    - DeviceFarmProject
    - DirectoryServiceDirectory
    - DynamoDBTable
    - DynamoDBTableItem
    - EC2Address
    - EC2ClientVpnEndpoint
    - EC2ClientVpnEndpointAttachment
    - EC2CustomerGateway
    - EC2DHCPOption
    - EC2DefaultSecurityGroupRule
    - EC2EgressOnlyInternetGateway
    - EC2Image
    - EC2Instance
    - EC2InternetGateway
    - EC2InternetGatewayAttachment
    - EC2KeyPair
    - EC2LaunchTemplate
    - EC2NATGateway
    - EC2NetworkACL
    - EC2NetworkInterface
    - EC2PlacementGroup
    - EC2RouteTable
    - EC2SecurityGroup
    - EC2Snapshot
    - EC2SpotFleetRequest
    - EC2Subnet
    - EC2TGW
    - EC2TGWAttachment
    - EC2VPC
    - EC2VPCEndpoint
    - EC2VPCEndpointServiceConfiguration
    - EC2VPCPeeringConnection
    - EC2VPNConnection
    - EC2VPNGateway
    - EC2VPNGatewayAttachment
    - EC2Volume
    - ECRRepository
    - ECSCluster
    - ECSClusterInstance
    - ECSService
    - ECSTaskDefinition
    - EFSFileSystem
    - EFSMountTarget
    - EKSCluster
    - EKSFargateProfiles
    - EKSNodegroups
    - ELB
    - ELBv2
    - ELBv2TargetGroup
    - EMRCluster
    - EMRSecurityConfiguration
    - ESDomain
    - ElasticBeanstalkApplication
    - ElasticBeanstalkEnvironment
    - ElasticTranscoderPipeline
    - ElasticacheCacheCluster
    - ElasticacheReplicationGroup
    - ElasticacheSubnetGroup
    - FMSNotificationChannel
    - FMSPolicy
    - FSxBackup
    - FSxFileSystem
    - FirehoseDeliveryStream
    - GlobalAccelerator
    - GlobalAcceleratorEndpointGroup
    - GlobalAcceleratorListener
    - GlueClassifier
    - GlueConnection
    - GlueCrawler
    - GlueDatabase
    - GlueDevEndpoint
    - GlueJob
    - GlueTrigger
    - GuardDutyDetector
    - IAMGroup
    - IAMGroupPolicy
    - IAMGroupPolicyAttachment
    - IAMInstanceProfile
    - IAMInstanceProfileRole
    - IAMLoginProfile
    - IAMOpenIDConnectProvider
    - IAMPolicy
    - IAMRole
    - IAMRolePolicy
    - IAMRolePolicyAttachment
    - IAMSAMLProvider
    - IAMServerCertificate
    - IAMServiceSpecificCredential
    - IAMSigningCertificate
    - IAMUser
    - IAMUserAccessKey
    - IAMUserGroupAttachment
    - IAMUserPolicy
    - IAMUserPolicyAttachment
    - IAMUserSSHPublicKey
    - IAMVirtualMFADevice
    - ImageBuilderComponent
    - ImageBuilderDistributionConfiguration
    - ImageBuilderImage
    - ImageBuilderInfrastructureConfiguration
    - ImageBuilderPipeline
    - ImageBuilderRecipe
    - InspectorAssessmentRun
    - InspectorAssessmentTarget
    - InspectorAssessmentTemplate
    - IoTAuthorizer
    - IoTCACertificate
    - IoTCertificate
    - IoTJob
    - IoTOTAUpdate
    - IoTPolicy
    - IoTRoleAlias
    - IoTStream
    - IoTThing
    - IoTThingGroup
    - IoTThingType
    - IoTThingTypeState
    - IoTTopicRule
    - KMSAlias
    - KMSKey
    - KendraIndex
    - KinesisAnalyticsApplication
    - KinesisStream
    - KinesisVideoProject
    - LambdaEventSourceMapping
    - LambdaFunction
    - LambdaLayer
    - LaunchConfiguration
    - LexBot
    - LexIntent
    - LexMod- elBuildingServiceBotAlias
    - LexSlotType
    - LifecycleHook
    - LightsailDisk
    - LightsailDomain
    - LightsailInstance
    - LightsailKeyPair
    - LightsailLoadBalancer
    - LightsailStaticIP
    - MQBroker
    - MSKCluster
    - MSKConfiguration
    - Macie
    - MediaConvertJobTemplate
    - MediaConvertPreset
    - MediaLiveChannel
    - MediaLiveInput
    - MediaLiveInputSecurityGroup
    - MediaPackageChannel
    - MediaPackageOriginEndpoint
    - MediaStoreContainer
    - MediaStoreDataItems
    - MediaTailorConfiguration
    - MediaConvertQueue
    - MobileProject
    - NeptuneCluster
    - NeptuneInstance
    - NetpuneSnapshot
    - OpsWorksApp
    - OpsWorksCMBackup
    - OpsWorksCMServer
    - OpsWorksCMServerState
    - OpsWorksInstance
    - OpsWorksLayer
    - OpsWorksUserProfile
    - RDSDBCluster
    - RDSDBClusterParameterGroup
    - RDSDBParameterGroup
    - RDSDBSubnetGroup
    - RDSEventSubscription
    - RDSInstance
    - RDSOptionGroup
    - RDSProxy
    - RDSSnapshot
    - RedshiftCluster
    - RedshiftParameterGroup
    - RedshiftSnapshot
    - RedshiftSubnetGroup
    - RekognitionCollection
    - ResourceGroupGroup
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - RoboMakerSimulationJob
    - Route53HealthCheck
    - Route53HostedZone
    - Route53ResolverEndpoint
    - Route53ResolverRule
    - Route53ResourceRecordSet
    - Route53TrafficPolicy
    - S3AccessPoint
    - S3Bucket
    - S3MultipartUpload
    - S3Object
    - SESConfigurationSet
    - SESIdentity
    - SESReceiptFilter
    - SESReceiptRuleSet
    - SESTemplate
    - SFNStateMachine
    - SNSEndpoint
    - SNSPlatformApplication
    - SNSSubscription
    - SNSTopic
    - SQSQueue
    - SSMActivation
    - SSMAssociation
    - SSMDocument
    - SSMMaintenanceWindow
    - SSMParameter
    - SSMPatchBaseline
    - SSMResourceDataSync
    - SageMakerApp
    - SageMakerDomain
    - SageMakerEndpoint
    - SageMakerEndpointConfig
    - SageMakerModel
    - SageMakerNotebookInstance
    - SageMakerNotebookInstanceLifecycleConfig
    - SageMakerNotebookInstanceState
    - SageMakerUserProfiles
    - SecretsManagerSecret
    - SecurityHub
    - ServiceCatalogConstraintPortfolioAttachment
    - ServiceCatalogPortfolio
    - ServiceCatalogPortfolioProductAttachment
    - ServiceCatalogPortfolioShareAttachment
    - ServiceCatalogPrincipalPortfolioAttachment
    - ServiceCatalogProduct
    - ServiceCatalogProvisionedProduct
    - ServiceCatalogTagOption
    - ServiceCatalogTagOptionPortfolioAttachment
    - ServiceDiscoveryInstance
    - ServiceDiscoveryNamespace
    - ServiceDiscoveryService
    - SimpleDBDomain
    - StorageGatewayFileShare
    - StorageGatewayGateway
    - StorageGatewayTape
    - StorageGatewayVolume
    - TransferServer
    - TransferServerUser
    - WAFRegionalByteMatchSet
    - WAFRegionalByteMatchSetIP
    - WAFRegionalIPSet
    - WAFRegionalIPSetIP
    - WAFRegionalRateBasedRule
    - WAFRegionalRateBasedRulePredicate
    - WAFRegionalRegexMatchSet
    - WAFRegionalRegexMatchTuple
    - WAFRegionalRegexPatternSet
    - WAFRegionalRegexPatternString
    - WAFRegionalRule
    - WAFRegionalRuleGroup
    - WAFRegionalRulePredicate
    - WAFRegionalWebACL
    - WAFRegionalWebACLRuleAttachment
    - WAFRule
    - WAFWebACL
    - WAFWebACLRuleAttachment
    - WAFv2IPSet
    - WAFv2RegexPatternSet
    - WAFv2RuleGroup
    - WAFv2WebACL
    - WorkLinkFleet
    - WorkSpacesWorkspace
    - XRayGroup
    - XRaySamplingRule

  # You can instead specify exclusion
  # Every resources will be deleted except excluded ones
  #
  # excludes:
  # - IAMUser
  # - IAMUserAccessKey
  # - IAMGroup
  # - IAMPolicy
  # - IAMRole
